"""image update

Revision ID: 2e3e21eadeaa
Revises: 35beb793f2b3
Create Date: 2018-12-01 16:46:23.453789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e3e21eadeaa'
down_revision = '35beb793f2b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kostym', 'obrazek')
    op.drop_column('doplnek', 'obrazek')
    op.add_column('doplnek', sa.Column('obrazek', sa.String(length=100)))
    op.add_column('kostym', sa.Column('obrazek', sa.String(length=100)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kostym', 'obrazek')
    op.drop_column('doplnek', 'obrazek')
    op.add_column('doplnek', sa.Column('obrazek', sa.LargeBinary))
    op.add_column('kostym', sa.Column('obrazek', sa.LargeBinary))
    # ### end Alembic commands ###
