"""update vypujcka

Revision ID: 35beb793f2b3
Revises: 8c70b57dac34
Create Date: 2018-11-29 15:08:45.022264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35beb793f2b3'
down_revision = '8c70b57dac34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vypujcka', sa.Column('datum_vraceni', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vypujcka', 'datum_vraceni')
    # ### end Alembic commands ###
