"""values update

Revision ID: 4044288fd3d0
Revises: 3fcb97bb3275
Create Date: 2018-10-04 17:35:24.250152

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4044288fd3d0'
down_revision = '3fcb97bb3275'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doplnek', 'stari')
    op.add_column('kostym', sa.Column('datum_vyroby', sa.Date(), nullable=False))
    op.drop_column('kostym', 'stari')
    op.add_column('osoba', sa.Column('tel_cislo', sa.String(length=10), nullable=True))
    op.create_unique_constraint(None, 'osoba', ['email'])
    op.drop_column('osoba', 'tel_cilo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('osoba', sa.Column('tel_cilo', mysql.VARCHAR(collation='utf8_czech_ci', length=10), nullable=True))
    op.drop_constraint(None, 'osoba', type_='unique')
    op.drop_column('osoba', 'tel_cislo')
    op.add_column('kostym', sa.Column('stari', sa.DATE(), nullable=False))
    op.drop_column('kostym', 'datum_vyroby')
    op.add_column('doplnek', sa.Column('stari', sa.DATE(), nullable=True))
    # ### end Alembic commands ###
