"""image path

Revision ID: 44923ffdec42
Revises: 5cf6b23adadf
Create Date: 2018-10-05 10:13:25.545296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44923ffdec42'
down_revision = '5cf6b23adadf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doplnek', sa.Column('obrazek', sa.String(length=100), nullable=True))
    op.add_column('kostym', sa.Column('obrazek', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kostym', 'obrazek')
    op.drop_column('doplnek', 'obrazek')
    # ### end Alembic commands ###
