"""base updates

Revision ID: 53f1e32580ae
Revises: 44923ffdec42
Create Date: 2018-10-25 18:09:01.646344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '53f1e32580ae'
down_revision = '44923ffdec42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('osoba_ibfk_1', 'osoba', type_='foreignkey')
    op.drop_column('osoba', 'obec_id')
    op.drop_column('vypujcka', 'cena')
    op.drop_table('obec')
    op.add_column('doplnek', sa.Column('cena', sa.Integer(), nullable=False))
    op.add_column('doplnek', sa.Column('vyrobce', sa.String(length=45), nullable=False))
    op.add_column('kostym', sa.Column('cena', sa.Integer(), nullable=False))
    op.add_column('kostym', sa.Column('nazev', sa.String(length=128), nullable=False))
    op.add_column('osoba', sa.Column('obec', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vypujcka', sa.Column('cena', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('osoba', sa.Column('obec_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('osoba_ibfk_1', 'osoba', 'obec', ['obec_id'], ['id'], ondelete='CASCADE')
    op.drop_column('osoba', 'obec')
    op.drop_column('kostym', 'nazev')
    op.drop_column('kostym', 'cena')
    op.drop_column('doplnek', 'vyrobce')
    op.drop_column('doplnek', 'cena')
    op.create_table('obec',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nazev', mysql.VARCHAR(collation='utf8_czech_ci', length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###
