"""image update

Revision ID: 8c70b57dac34
Revises: 5cf6b23adadf
Create Date: 2018-10-28 17:07:56.756306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c70b57dac34'
down_revision = '5cf6b23adadf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kostym', 'obrazek')
    op.drop_column('doplnek', 'obrazek')
    op.add_column('doplnek', sa.Column('obrazek', sa.LargeBinary, nullable=True))
    op.add_column('kostym', sa.Column('obrazek', sa.LargeBinary, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kostym', 'obrazek')
    op.drop_column('doplnek', 'obrazek')
    op.add_column('doplnek', sa.Column('obrazek', sa.String(length=100), nullable=True))
    op.add_column('kostym', sa.Column('obrazek', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###
