"""init

Revision ID: c3b684aaffee
Revises: 
Create Date: 2018-10-01 20:42:51.195708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3b684aaffee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barva',
    sa.Column('barva', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('barva')
    )
    op.create_table('doplnek',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazev', sa.String(length=128), nullable=False),
    sa.Column('stari', sa.Date(), nullable=True),
    sa.Column('popis_vyuziti', sa.String(length=512), nullable=False),
    sa.Column('datum_vyroby', sa.Date(), nullable=True),
    sa.Column('velikost', sa.Enum('S', 'M', 'L', 'XL', 'XXL', 'XXXL'), nullable=True),
    sa.Column('typ', sa.String(length=45), nullable=True),
    sa.Column('material', sa.String(length=45), nullable=False),
    sa.Column('pocet', sa.Integer(), nullable=True),
    sa.Column('opotrebeni', sa.Enum('nove', 'stare', 'zanovni'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kostym',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vyrobce', sa.String(length=45), nullable=False),
    sa.Column('material', sa.String(length=45), nullable=False),
    sa.Column('popis', sa.String(length=512), nullable=False),
    sa.Column('velikost', sa.Enum('S', 'M', 'L', 'XL', 'XXL', 'XXXL'), nullable=True),
    sa.Column('stari', sa.Date(), nullable=False),
    sa.Column('opotrebeni', sa.Enum('nove', 'stare', 'zanovni'), nullable=True),
    sa.Column('pocet', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obec',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazev', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vyuziti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('druh_akce', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('barva_kostym',
    sa.Column('kostym_id', sa.Integer(), nullable=False),
    sa.Column('barva', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['barva'], ['barva.barva'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kostym_id'], ['kostym.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('kostym_id', 'barva')
    )
    op.create_table('doplnek_barva',
    sa.Column('doplnek_id', sa.Integer(), nullable=False),
    sa.Column('barva', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['barva'], ['barva.barva'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doplnek_id'], ['doplnek.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doplnek_id', 'barva')
    )
    op.create_table('kostym_vyuziti',
    sa.Column('kostym_id', sa.Integer(), nullable=False),
    sa.Column('vyuziti_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kostym_id'], ['kostym.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vyuziti_id'], ['vyuziti.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('kostym_id', 'vyuziti_id')
    )
    op.create_table('osoba',
    sa.Column('rc', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('heslo', sa.String(length=256), nullable=True),
    sa.Column('jmeno', sa.String(length=128), nullable=False),
    sa.Column('prijmeni', sa.String(length=128), nullable=False),
    sa.Column('ulice', sa.String(length=256), nullable=True),
    sa.Column('cislo_popisne', sa.Integer(), nullable=True),
    sa.Column('tel_cilo', sa.Integer(), nullable=True),
    sa.Column('obec_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['obec_id'], ['obec.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rc')
    )
    op.create_table('klient',
    sa.Column('clenstvi', sa.Enum('zlate', 'stribrne', 'bronzove'), nullable=True),
    sa.Column('osoba_rc', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['osoba_rc'], ['osoba.rc'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('osoba_rc')
    )
    op.create_table('vypujcka',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazev_akce', sa.String(length=256), nullable=False),
    sa.Column('datum_vypujceni', sa.Date(), nullable=False),
    sa.Column('vracen', sa.Integer(), nullable=False),
    sa.Column('cena', sa.Integer(), nullable=False),
    sa.Column('klient', sa.String(length=10), nullable=True),
    sa.Column('zamestnanec', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['klient'], ['osoba.rc'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zamestnanec'], ['osoba.rc'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zamestnanec',
    sa.Column('pozice', sa.Enum('zamestnanec', 'vedouci'), nullable=True),
    sa.Column('osoba_rc', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['osoba_rc'], ['osoba.rc'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('osoba_rc')
    )
    op.create_table('doplnek_vypujcka',
    sa.Column('doplnek_id', sa.Integer(), nullable=False),
    sa.Column('vypujcka_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doplnek_id'], ['doplnek.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vypujcka_id'], ['vypujcka.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doplnek_id', 'vypujcka_id')
    )
    op.create_table('vypujcka_kostym',
    sa.Column('vypujcka_id', sa.Integer(), nullable=False),
    sa.Column('kostym_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kostym_id'], ['kostym.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vypujcka_id'], ['vypujcka.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vypujcka_id', 'kostym_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vypujcka_kostym')
    op.drop_table('doplnek_vypujcka')
    op.drop_table('zamestnanec')
    op.drop_table('vypujcka')
    op.drop_table('klient')
    op.drop_table('osoba')
    op.drop_table('kostym_vyuziti')
    op.drop_table('doplnek_barva')
    op.drop_table('barva_kostym')
    op.drop_table('vyuziti')
    op.drop_table('obec')
    op.drop_table('kostym')
    op.drop_table('doplnek')
    op.drop_table('barva')
    # ### end Alembic commands ###
