"""removed barva column

Revision ID: c7a78c49e5c0
Revises: 015f0dc67c12
Create Date: 2018-12-03 16:23:47.953940

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7a78c49e5c0'
down_revision = '015f0dc67c12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doplnek_barva')
    op.drop_table('barva_kostym')
    op.drop_table('barva')
    op.add_column('doplnek', sa.Column('barva', sa.String(length=45), nullable=False))
    op.add_column('kostym', sa.Column('barva', sa.String(length=45), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kostym', 'barva')
    op.drop_column('doplnek', 'barva')
    op.create_table('barva',
    sa.Column('barva', mysql.VARCHAR(collation='utf8_czech_ci', length=20), nullable=False),
    sa.PrimaryKeyConstraint('barva'),
    mysql_collate='utf8_czech_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('barva_kostym',
    sa.Column('kostym_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('barva', mysql.VARCHAR(collation='utf8_czech_ci', length=20), nullable=False),
    sa.ForeignKeyConstraint(['barva'], ['barva.barva'], name='barva_kostym_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kostym_id'], ['kostym.id'], name='barva_kostym_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('kostym_id', 'barva'),
    mysql_collate='utf8_czech_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('doplnek_barva',
    sa.Column('doplnek_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('barva', mysql.VARCHAR(collation='utf8_czech_ci', length=20), nullable=False),
    sa.ForeignKeyConstraint(['barva'], ['barva.barva'], name='doplnek_barva_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doplnek_id'], ['doplnek.id'], name='doplnek_barva_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doplnek_id', 'barva'),
    mysql_collate='utf8_czech_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
